/* Generated by re2c 0.13.5 */
/**
 * Clever programming language
 * Copyright (c) Clever Team
 *
 * This file is distributed under the MIT license. See LICENSE for details.
 */

#include <cstdio>
#include "core/scanner.h"
#include "core/parser.hh"
#include "core/ast.h"
#include "core/value.h"
#include "core/native_types.h"

namespace clever {

typedef Parser::token token;

Parser::token_type yylex(Parser::semantic_type* yylval,
	Parser::location_type* yyloc, Driver& driver, ScannerState& s) {
	const unsigned char* cursor = s.cur;
	int yylen;

next_token:
	if (YYCURSOR >= YYLIMIT) {
		RET(token::END);
	}

	s.yylex = cursor;


{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if (YYGETCONDITION() < 1) {
		goto yyc_INITIAL;
	} else {
		if (YYGETCONDITION() < 2) {
			goto yyc_ST_COMMENT;
		} else {
			goto yyc_ST_MULTILINE_COMMENT;
		}
	}
/* *********************************** */
yyc_INITIAL:
	{
		static const unsigned char yybm[] = {
			/* table 1 .. 8: 0 */
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40, 168, 104, 168,  40, 168,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			168,  40,   8,  40,  40,  40,  40,  32, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 47,  47,  47,  47,  47,  47,  47,  47, 
			 45,  45,  40,  40,  40,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  16,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			/* table 9 .. 10: 256 */
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192,   0,   0,   0,   0,   0,   0, 
			  0, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192,   0,   0,   0,   0, 192, 
			  0,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};

		yych = *YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy2;
		case '\t':
		case '\v':
		case '\r':
		case ' ':	goto yy5;
		case '\n':	goto yy7;
		case '!':	goto yy9;
		case '"':	goto yy10;
		case '#':	goto yy11;
		case '%':	goto yy13;
		case '&':	goto yy14;
		case '\'':	goto yy16;
		case '(':
		case ')':
		case ',':
		case ';':
		case '{':
		case '}':
		case '~':	goto yy17;
		case '*':	goto yy18;
		case '+':	goto yy19;
		case '-':	goto yy20;
		case '.':	goto yy21;
		case '/':	goto yy22;
		case '0':	goto yy23;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy25;
		case '<':	goto yy26;
		case '=':	goto yy28;
		case '>':	goto yy29;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':	goto yy31;
		case '^':	goto yy33;
		case '_':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'q':
		case 'u':
		case 'x':
		case 'y':
		case 'z':	goto yy34;
		case 'a':	goto yy36;
		case 'b':	goto yy37;
		case 'c':	goto yy38;
		case 'd':	goto yy39;
		case 'e':	goto yy40;
		case 'f':	goto yy41;
		case 'i':	goto yy42;
		case 'n':	goto yy43;
		case 'o':	goto yy44;
		case 'p':	goto yy45;
		case 'r':	goto yy46;
		case 's':	goto yy47;
		case 't':	goto yy48;
		case 'v':	goto yy49;
		case 'w':	goto yy50;
		case '|':	goto yy51;
		default:	goto yy4;
		}
yy2:
		++YYCURSOR;
yy3:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy4:
		yych = *++YYCURSOR;
		goto yy3;
yy5:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy287;
yy6:
		{ yylen = cursor - s.yylex; }
		{ yyloc->step(); SKIP(); }
yy7:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy285;
yy8:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy9:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy282;
		goto yy3;
yy10:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy278;
yy11:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy13:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy275;
		goto yy3;
yy14:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '&') goto yy273;
		if (yych == '=') goto yy271;
yy15:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy16:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy265;
yy17:
		yych = *++YYCURSOR;
		goto yy15;
yy18:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy262;
		goto yy15;
yy19:
		yych = *++YYCURSOR;
		if (yych == '+') goto yy260;
		if (yych == '=') goto yy258;
		goto yy15;
yy20:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') {
			if (yych <= ',') goto yy15;
			if (yych <= '-') goto yy256;
			if (yych <= '.') goto yy253;
			goto yy15;
		} else {
			if (yych <= '9') goto yy251;
			if (yych == '=') goto yy254;
			goto yy15;
		}
yy21:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy249;
		goto yy3;
yy22:
		yych = *++YYCURSOR;
		if (yych <= '.') {
			if (yych == '*') goto yy243;
			goto yy15;
		} else {
			if (yych <= '/') goto yy245;
			if (yych == '=') goto yy247;
			goto yy15;
		}
yy23:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'x') goto yy239;
		goto yy238;
yy24:
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex);
		int64_t n = 0;

		for (int i = 0; i < yylen; ++i) {
			n = n * 10 + (nstr[i] - '0');
		}

		yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy25:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy229;
yy26:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= ';') goto yy27;
		if (yych <= '<') goto yy221;
		if (yych <= '=') goto yy223;
yy27:
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS); }
yy28:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy219;
		goto yy15;
yy29:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '<') goto yy30;
		if (yych <= '=') goto yy215;
		if (yych <= '>') goto yy213;
yy30:
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER); }
yy31:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy209;
yy32:
		{ yylen = cursor - s.yylex; }
		{
		yylval->ident = new ast::Ident(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);

		RET(token::CONSTANT);
	}
yy33:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy206;
		goto yy15;
yy34:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy57;
yy35:
		{ yylen = cursor - s.yylex; }
		{
		yylval->ident = new ast::Ident(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);

		RET(token::IDENT);
	}
yy36:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy203;
		goto yy57;
yy37:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy198;
		goto yy57;
yy38:
		yych = *++YYCURSOR;
		switch (yych) {
		case 'a':	goto yy166;
		case 'l':	goto yy167;
		case 'o':	goto yy168;
		case 'r':	goto yy169;
		default:	goto yy57;
		}
yy39:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy159;
		goto yy57;
yy40:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy148;
		goto yy57;
yy41:
		yych = *++YYCURSOR;
		if (yych <= 'i') {
			if (yych == 'a') goto yy125;
			if (yych <= 'h') goto yy57;
			goto yy126;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy57;
				goto yy127;
			} else {
				if (yych == 'u') goto yy128;
				goto yy57;
			}
		}
yy42:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy117;
		if (yych == 'm') goto yy119;
		goto yy57;
yy43:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy110;
		if (yych == 'u') goto yy111;
		goto yy57;
yy44:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy108;
		goto yy57;
yy45:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy89;
		if (yych == 'u') goto yy90;
		goto yy57;
yy46:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy83;
		goto yy57;
yy47:
		yych = *++YYCURSOR;
		if (yych == 'w') goto yy77;
		goto yy57;
yy48:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy66;
		if (yych == 'r') goto yy67;
		goto yy57;
yy49:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy63;
		goto yy57;
yy50:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy58;
		goto yy57;
yy51:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy52;
		if (yych == '|') goto yy54;
		goto yy15;
yy52:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_OR_EQUAL); }
yy54:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_OR); }
yy56:
		++YYCURSOR;
		yych = *YYCURSOR;
yy57:
		if (yybm[256+yych] & 64) {
			goto yy56;
		}
		goto yy35;
yy58:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::WHILE);
	}
yy63:
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::VAR); }
yy66:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy73;
		goto yy57;
yy67:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy70;
		if (yych != 'y') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::TRY); }
yy70:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->true_ = new ast::TrueLit(*yyloc);
		RET(token::TRUE);
	}
yy73:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::THROW); }
yy77:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::SWITCH); }
yy83:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::RETURN);
	}
yy89:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy96;
		if (yych == 'o') goto yy97;
		goto yy57;
yy90:
		yych = *++YYCURSOR;
		if (yych != 'b') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::PUBLIC); }
yy96:
		yych = *++YYCURSOR;
		if (yych == 'v') goto yy103;
		goto yy57;
yy97:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::THREAD);
	}
yy103:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::PRIVATE); }
yy108:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_OR); }
yy110:
		yych = *++YYCURSOR;
		if (yych == 'w') goto yy115;
		goto yy57;
yy111:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->nillit = new ast::NullLit(*yyloc);
		RET(token::NIL);
	}
yy115:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::NEW);
	}
yy117:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IF);
	}
yy119:
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IMPORT);
	}
yy125:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy144;
		goto yy57;
yy126:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy138;
		goto yy57;
yy127:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy136;
		goto yy57;
yy128:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FUNC);
	}
yy136:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FOR);
	}
yy138:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'y') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::FINALLY); }
yy144:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->false_ = new ast::FalseLit(*yyloc);
		RET(token::FALSE);
	}
yy148:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'Z') {
			if (yych <= '/') {
				if (yych == ' ') goto yy153;
			} else {
				if (yych <= '9') goto yy56;
				if (yych >= 'A') goto yy56;
			}
		} else {
			if (yych <= '`') {
				if (yych == '_') goto yy56;
			} else {
				if (yych == 'i') goto yy152;
				if (yych <= 'z') goto yy56;
			}
		}
yy151:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSE);
	}
yy152:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy158;
		goto yy57;
yy153:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy155;
yy154:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy3;
				} else {
					goto yy15;
				}
			} else {
				goto yy24;
			}
		} else {
			if (yyaccept <= 4) {
				if (yyaccept <= 3) {
					goto yy151;
				} else {
					goto yy234;
				}
			} else {
				goto yy267;
			}
		}
yy155:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy154;
		++YYCURSOR;
yy157:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSEIF);
	}
yy158:
		yych = *++YYCURSOR;
		if (yybm[256+yych] & 64) {
			goto yy56;
		}
		goto yy157;
yy159:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::DEFAULT); }
yy166:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy57;
		if (yych <= 's') goto yy191;
		if (yych <= 't') goto yy192;
		goto yy57;
yy167:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy187;
		goto yy57;
yy168:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy177;
		goto yy57;
yy169:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::CRITICAL);
	}
yy177:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy57;
		if (yych <= 's') goto yy178;
		if (yych <= 't') goto yy179;
		goto yy57;
yy178:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy185;
		goto yy57;
yy179:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONTINUE); }
yy185:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONST); }
yy187:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 's') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::CLASS);
	}
yy191:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy196;
		goto yy57;
yy192:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CATCH); }
yy196:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CASE); }
yy198:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy57;
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::BREAK);
	}
yy203:
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy57;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy56;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_AND); }
yy206:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::XOR_EQUAL); }
yy208:
		++YYCURSOR;
		yych = *YYCURSOR;
yy209:
		if (yybm[256+yych] & 128) {
			goto yy208;
		}
		if (yych <= '`') goto yy32;
		if (yych >= '{') goto yy32;
yy210:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'Z') {
			if (yych <= '/') goto yy212;
			if (yych <= '9') goto yy210;
			if (yych >= 'A') goto yy210;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yy210;
			} else {
				if (yych <= '`') goto yy212;
				if (yych <= 'z') goto yy210;
			}
		}
yy212:
		{ yylen = cursor - s.yylex; }
		{
		yylval->type = new ast::Type(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);
		RET(token::TYPE);
	}
yy213:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy217;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT); }
yy215:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER_EQUAL); }
yy217:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT_EQUAL); }
yy219:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::EQUAL); }
yy221:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy225;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT); }
yy223:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS_EQUAL); }
yy225:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT_EQUAL); }
yy227:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy154;
		if (yych <= '9') goto yy235;
		goto yy154;
yy228:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy229:
		if (yybm[0+yych] & 1) {
			goto yy228;
		}
		if (yych <= 'D') {
			if (yych == '.') goto yy227;
			goto yy24;
		} else {
			if (yych <= 'E') goto yy230;
			if (yych != 'e') goto yy24;
		}
yy230:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych != '+') goto yy154;
		} else {
			if (yych <= '-') goto yy231;
			if (yych <= '/') goto yy154;
			if (yych <= '9') goto yy232;
			goto yy154;
		}
yy231:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy154;
		if (yych >= ':') goto yy154;
yy232:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= '/') goto yy234;
		if (yych <= '9') goto yy232;
yy234:
		{ yylen = cursor - s.yylex; }
		{
		double n = strtod(
			std::string(reinterpret_cast<const char*>(s.yylex), yylen).c_str(), NULL);

        yylval->dbllit = new ast::DoubleLit(n, *yyloc);

		RET(token::NUM_DOUBLE);
	}
yy235:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy234;
			if (yych <= '9') goto yy235;
			goto yy234;
		} else {
			if (yych <= 'E') goto yy230;
			if (yych == 'e') goto yy230;
			goto yy234;
		}
yy237:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy238:
		if (yybm[0+yych] & 2) {
			goto yy237;
		}
		if (yych <= '9') {
			if (yych == '.') goto yy227;
			if (yych <= '/') goto yy24;
			goto yy228;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy24;
				goto yy230;
			} else {
				if (yych == 'e') goto yy230;
				goto yy24;
			}
		}
yy239:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy240;
		}
		goto yy154;
yy240:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy240;
		}
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex + 2);
		int64_t n = 0;

		for (int i = 0; i < yylen - 2; ++i) {
			n <<= 4;
			if (isdigit(nstr[i])) {
				n += nstr[i] - '0';
			}
			else {
				n += toupper(nstr[i]) - 'A' + 10;
			}
		}

		yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy243:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_MULTILINE_COMMENT);
		SKIP();
	}
yy245:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy247:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DIV_EQUAL); }
yy249:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy234;
			if (yych <= '9') goto yy249;
			goto yy234;
		} else {
			if (yych <= 'E') goto yy230;
			if (yych == 'e') goto yy230;
			goto yy234;
		}
yy251:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych == '.') goto yy227;
		if (yych <= '/') goto yy154;
		if (yych <= '9') goto yy251;
		goto yy154;
yy253:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy154;
		if (yych <= '9') goto yy249;
		goto yy154;
yy254:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MINUS_EQUAL); }
yy256:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DEC); }
yy258:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::PLUS_EQUAL); }
yy260:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::INC); }
yy262:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MULT_EQUAL); }
yy264:
		++YYCURSOR;
		yych = *YYCURSOR;
yy265:
		if (yybm[0+yych] & 8) {
			goto yy264;
		}
		if (yych >= '\\') goto yy268;
yy266:
		++YYCURSOR;
yy267:
		{ yylen = cursor - s.yylex; }
		{
		std::string strtext(reinterpret_cast<const char*>(s.yylex+1), yylen-2);
		size_t found = 0;

		// Handle sequence char
		while (1) {
			found = strtext.find('\\', found);
			if (found == std::string::npos) {
				break;
			}
			if (s.yylex[0] == '"') {
				switch (strtext[found+1]) {
					case 'n': strtext.replace(found, 2, 1, '\n'); break;
					case 'r': strtext.replace(found, 2, 1, '\r'); break;
					case 't': strtext.replace(found, 2, 1, '\t'); break;
					case 'v': strtext.replace(found, 2, 1, '\v'); break;
					case '"': strtext.replace(found, 2, 1, '"'); break;
					case '\\': strtext.replace(found, 2, 1, '\\'); ++found; break;
					default: ++found; break;
				}
			} else {
				switch (strtext[found+1]) {
					case '\'': strtext.replace(found, 2, 1, '\''); break;
					default: ++found; break;
				}
			}
		}

        yylval->strlit = new ast::StringLit(CSTRING(strtext), *yyloc);

		RET(token::STR);
	}
yy268:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy264;
		}
		if (yych >= '\\') goto yy268;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy264;
		}
		if (yych <= '[') goto yy266;
		goto yy268;
yy271:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_AND_EQUAL); }
yy273:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_AND); }
yy275:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MOD_EQUAL); }
yy277:
		++YYCURSOR;
		yych = *YYCURSOR;
yy278:
		if (yybm[0+yych] & 32) {
			goto yy277;
		}
		if (yych <= '[') goto yy266;
yy279:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy277;
		}
		if (yych >= '\\') goto yy279;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy277;
		}
		if (yych <= '[') goto yy266;
		goto yy279;
yy282:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::NOT_EQUAL); }
yy284:
		++YYCURSOR;
		yych = *YYCURSOR;
yy285:
		if (yybm[0+yych] & 64) {
			goto yy284;
		}
		goto yy8;
yy286:
		++YYCURSOR;
		yych = *YYCURSOR;
yy287:
		if (yybm[0+yych] & 128) {
			goto yy286;
		}
		goto yy6;
	}
/* *********************************** */
yyc_ST_COMMENT:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,  32, 192,  64, 192,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yych <= '\v') {
			if (yych <= 0x08) {
				if (yych <= 0x00) goto yy291;
				goto yy292;
			} else {
				if (yych == '\n') goto yy294;
				goto yy293;
			}
		} else {
			if (yych <= '\r') {
				if (yych <= '\f') goto yy292;
				goto yy293;
			} else {
				if (yych == ' ') goto yy293;
				goto yy292;
			}
		}
yy290:
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy291:
		yych = *++YYCURSOR;
		goto yy299;
yy292:
		yych = *++YYCURSOR;
		goto yy299;
yy293:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy300;
		}
		if (yych == '\n') goto yy290;
		goto yy298;
yy294:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy297;
yy295:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy296:
		++YYCURSOR;
		yych = *YYCURSOR;
yy297:
		if (yybm[0+yych] & 32) {
			goto yy296;
		}
		goto yy295;
yy298:
		++YYCURSOR;
		yych = *YYCURSOR;
yy299:
		if (yybm[0+yych] & 64) {
			goto yy298;
		}
		goto yy290;
yy300:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy300;
		}
		if (yych == '\n') goto yy290;
		goto yy298;
	}
/* *********************************** */
yyc_ST_MULTILINE_COMMENT:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,  32, 192,  64, 192,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,   0,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yych <= '\f') {
			if (yych <= '\t') {
				if (yych <= 0x00) goto yy304;
				if (yych <= 0x08) goto yy306;
				goto yy307;
			} else {
				if (yych <= '\n') goto yy308;
				if (yych <= '\v') goto yy307;
				goto yy306;
			}
		} else {
			if (yych <= ' ') {
				if (yych <= '\r') goto yy307;
				if (yych <= 0x1F) goto yy306;
				goto yy307;
			} else {
				if (yych == '*') goto yy310;
				goto yy306;
			}
		}
yy304:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy317;
yy305:
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy306:
		yych = *++YYCURSOR;
		goto yy317;
yy307:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy318;
		}
		goto yy317;
yy308:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy315;
yy309:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy310:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '/') goto yy312;
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy312:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy314:
		++YYCURSOR;
		yych = *YYCURSOR;
yy315:
		if (yybm[0+yych] & 32) {
			goto yy314;
		}
		goto yy309;
yy316:
		++YYCURSOR;
		yych = *YYCURSOR;
yy317:
		if (yybm[0+yych] & 64) {
			goto yy316;
		}
		goto yy305;
yy318:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy318;
		}
		if (yych == '\n') goto yy305;
		if (yych == '*') goto yy305;
		goto yy316;
	}
}

}

} // clever
