/* Generated by re2c 0.13.5 */
/**
 * Clever programming language
 * Copyright (c) Clever Team
 *
 * This file is distributed under the MIT license. See LICENSE for details.
 */

#include <cstdio>
#include "core/scanner.h"
#include "core/parser.hh"
#include "core/ast.h"
#include "core/value.h"
#include "types/native_types.h"

namespace clever {

typedef Parser::token token;

Parser::token_type yylex(Parser::semantic_type* yylval,
	Parser::location_type* yyloc, Driver& driver, ScannerState& s) {
	const unsigned char* cursor = s.cur;
	int yylen;

next_token:
	if (YYCURSOR >= YYLIMIT) {
		RET(token::END);
	}

	s.yylex = cursor;


{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if (YYGETCONDITION() < 1) {
		goto yyc_INITIAL;
	} else {
		if (YYGETCONDITION() < 2) {
			goto yyc_ST_COMMENT;
		} else {
			goto yyc_ST_MULTILINE_COMMENT;
		}
	}
/* *********************************** */
yyc_INITIAL:
	{
		static const unsigned char yybm[] = {
			/* table 1 .. 8: 0 */
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40, 168, 104, 168,  40, 168,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			168,  40,   8,  40,  40,  40,  40,  32, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 47,  47,  47,  47,  47,  47,  47,  47, 
			 45,  45,  40,  40,  40,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  16,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			/* table 9 .. 9: 256 */
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128,   0,   0,   0,   0,   0,   0, 
			  0, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128,   0,   0,   0,   0, 128, 
			  0, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};

		yych = *YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy2;
		case '\t':
		case '\v':
		case '\r':
		case ' ':	goto yy5;
		case '\n':	goto yy7;
		case '!':	goto yy9;
		case '"':	goto yy10;
		case '#':	goto yy11;
		case '%':	goto yy13;
		case '&':	goto yy14;
		case '\'':	goto yy16;
		case '(':
		case ')':
		case ',':
		case ';':
		case '{':
		case '}':
		case '~':	goto yy17;
		case '*':	goto yy18;
		case '+':	goto yy19;
		case '-':	goto yy20;
		case '.':	goto yy21;
		case '/':	goto yy22;
		case '0':	goto yy23;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy25;
		case '<':	goto yy26;
		case '=':	goto yy28;
		case '>':	goto yy29;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':	goto yy31;
		case '^':	goto yy33;
		case 'a':	goto yy34;
		case 'b':	goto yy36;
		case 'c':	goto yy37;
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'u':
		case 'x':
		case 'y':
		case 'z':	goto yy38;
		case 'e':	goto yy39;
		case 'f':	goto yy40;
		case 'i':	goto yy41;
		case 'n':	goto yy42;
		case 'o':	goto yy43;
		case 'r':	goto yy44;
		case 's':	goto yy45;
		case 't':	goto yy46;
		case 'v':	goto yy47;
		case 'w':	goto yy48;
		case '|':	goto yy49;
		default:	goto yy4;
		}
yy2:
		++YYCURSOR;
yy3:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy4:
		yych = *++YYCURSOR;
		goto yy3;
yy5:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy251;
yy6:
		{ yylen = cursor - s.yylex; }
		{ yyloc->step(); SKIP(); }
yy7:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy249;
yy8:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy9:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy246;
		goto yy3;
yy10:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy242;
yy11:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy13:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy239;
		goto yy3;
yy14:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '&') goto yy237;
		if (yych == '=') goto yy235;
yy15:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy16:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy229;
yy17:
		yych = *++YYCURSOR;
		goto yy15;
yy18:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy226;
		goto yy15;
yy19:
		yych = *++YYCURSOR;
		if (yych == '+') goto yy224;
		if (yych == '=') goto yy222;
		goto yy15;
yy20:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') {
			if (yych <= ',') goto yy15;
			if (yych <= '-') goto yy220;
			if (yych <= '.') goto yy217;
			goto yy15;
		} else {
			if (yych <= '9') goto yy215;
			if (yych == '=') goto yy218;
			goto yy15;
		}
yy21:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy213;
		goto yy3;
yy22:
		yych = *++YYCURSOR;
		if (yych <= '.') {
			if (yych == '*') goto yy207;
			goto yy15;
		} else {
			if (yych <= '/') goto yy209;
			if (yych == '=') goto yy211;
			goto yy15;
		}
yy23:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'x') goto yy203;
		goto yy202;
yy24:
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex);
		int64_t n = 0;

		for (int i = 0; i < yylen; ++i) {
			n = n * 10 + (nstr[i] - '0');
		}

        yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy25:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy193;
yy26:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= ';') goto yy27;
		if (yych <= '<') goto yy185;
		if (yych <= '=') goto yy187;
yy27:
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS); }
yy28:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy183;
		goto yy15;
yy29:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '<') goto yy30;
		if (yych <= '=') goto yy179;
		if (yych <= '>') goto yy177;
yy30:
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER); }
yy31:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy176;
yy32:
		{ yylen = cursor - s.yylex; }
		{
		yylval->type = new ast::Type(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);
		RET(token::TYPE);
	}
yy33:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy173;
		goto yy15;
yy34:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == 'n') goto yy170;
		goto yy55;
yy35:
		{ yylen = cursor - s.yylex; }
		{
		yylval->ident = new ast::Ident(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);

		RET(token::IDENT);
	}
yy36:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy165;
		goto yy55;
yy37:
		yych = *++YYCURSOR;
		if (yych <= 'n') {
			if (yych == 'a') goto yy141;
			goto yy55;
		} else {
			if (yych <= 'o') goto yy142;
			if (yych == 'r') goto yy143;
			goto yy55;
		}
yy38:
		yych = *++YYCURSOR;
		goto yy55;
yy39:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy130;
		goto yy55;
yy40:
		yych = *++YYCURSOR;
		if (yych <= 'i') {
			if (yych == 'a') goto yy107;
			if (yych <= 'h') goto yy55;
			goto yy108;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy55;
				goto yy109;
			} else {
				if (yych == 'u') goto yy110;
				goto yy55;
			}
		}
yy41:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy99;
		if (yych == 'm') goto yy101;
		goto yy55;
yy42:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy92;
		if (yych == 'u') goto yy93;
		goto yy55;
yy43:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy90;
		goto yy55;
yy44:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy84;
		goto yy55;
yy45:
		yych = *++YYCURSOR;
		if (yych == 'p') goto yy79;
		goto yy55;
yy46:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy68;
		if (yych == 'r') goto yy69;
		goto yy55;
yy47:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy65;
		goto yy55;
yy48:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy56;
		if (yych == 'h') goto yy57;
		goto yy55;
yy49:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy50;
		if (yych == '|') goto yy52;
		goto yy15;
yy50:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_OR_EQUAL); }
yy52:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_OR); }
yy54:
		++YYCURSOR;
		yych = *YYCURSOR;
yy55:
		if (yybm[256+yych] & 128) {
			goto yy54;
		}
		goto yy35;
yy56:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy62;
		goto yy55;
yy57:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::WHILE);
	}
yy62:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::WAIT);
	}
yy65:
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::VAR); }
yy68:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy75;
		goto yy55;
yy69:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy72;
		if (yych != 'y') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::TRY); }
yy72:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->true_ = new ast::TrueLit(*yyloc);
		RET(token::TRUE);
	}
yy75:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::THROW); }
yy79:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::THREAD);
	}
yy84:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::RETURN);
	}
yy90:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_OR); }
yy92:
		yych = *++YYCURSOR;
		if (yych == 'w') goto yy97;
		goto yy55;
yy93:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->nillit = new ast::NullLit(*yyloc);
		RET(token::NIL);
	}
yy97:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::NEW);
	}
yy99:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IF);
	}
yy101:
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IMPORT);
	}
yy107:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy126;
		goto yy55;
yy108:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy120;
		goto yy55;
yy109:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy118;
		goto yy55;
yy110:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FUNC);
	}
yy118:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FOR);
	}
yy120:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'y') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::FINALLY); }
yy126:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->false_ = new ast::FalseLit(*yyloc);
		RET(token::FALSE);
	}
yy130:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'Z') {
			if (yych <= '/') {
				if (yych == ' ') goto yy135;
			} else {
				if (yych <= '9') goto yy54;
				if (yych >= 'A') goto yy54;
			}
		} else {
			if (yych <= '`') {
				if (yych == '_') goto yy54;
			} else {
				if (yych == 'i') goto yy134;
				if (yych <= 'z') goto yy54;
			}
		}
yy133:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSE);
	}
yy134:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy140;
		goto yy55;
yy135:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy137;
yy136:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy3;
				} else {
					goto yy15;
				}
			} else {
				goto yy24;
			}
		} else {
			if (yyaccept <= 4) {
				if (yyaccept <= 3) {
					goto yy133;
				} else {
					goto yy198;
				}
			} else {
				goto yy231;
			}
		}
yy137:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy136;
		++YYCURSOR;
yy139:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSEIF);
	}
yy140:
		yych = *++YYCURSOR;
		if (yybm[256+yych] & 128) {
			goto yy54;
		}
		goto yy139;
yy141:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy161;
		goto yy55;
yy142:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy151;
		goto yy55;
yy143:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::CRITICAL);
	}
yy151:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy55;
		if (yych <= 's') goto yy152;
		if (yych <= 't') goto yy153;
		goto yy55;
yy152:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy159;
		goto yy55;
yy153:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONTINUE); }
yy159:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONST); }
yy161:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CATCH); }
yy165:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::BREAK);
	}
yy170:
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 128) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_AND); }
yy173:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::XOR_EQUAL); }
yy175:
		++YYCURSOR;
		yych = *YYCURSOR;
yy176:
		if (yych <= 'Z') {
			if (yych <= '/') goto yy32;
			if (yych <= '9') goto yy175;
			if (yych <= '@') goto yy32;
			goto yy175;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yy32;
				goto yy175;
			} else {
				if (yych <= '`') goto yy32;
				if (yych <= 'z') goto yy175;
				goto yy32;
			}
		}
yy177:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy181;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT); }
yy179:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER_EQUAL); }
yy181:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT_EQUAL); }
yy183:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::EQUAL); }
yy185:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy189;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT); }
yy187:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS_EQUAL); }
yy189:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT_EQUAL); }
yy191:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy136;
		if (yych <= '9') goto yy199;
		goto yy136;
yy192:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy193:
		if (yybm[0+yych] & 1) {
			goto yy192;
		}
		if (yych <= 'D') {
			if (yych == '.') goto yy191;
			goto yy24;
		} else {
			if (yych <= 'E') goto yy194;
			if (yych != 'e') goto yy24;
		}
yy194:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych != '+') goto yy136;
		} else {
			if (yych <= '-') goto yy195;
			if (yych <= '/') goto yy136;
			if (yych <= '9') goto yy196;
			goto yy136;
		}
yy195:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy136;
		if (yych >= ':') goto yy136;
yy196:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= '/') goto yy198;
		if (yych <= '9') goto yy196;
yy198:
		{ yylen = cursor - s.yylex; }
		{
		double n = strtod(
			std::string(reinterpret_cast<const char*>(s.yylex), yylen).c_str(), NULL);

        yylval->dbllit = new ast::DoubleLit(n, *yyloc);

		RET(token::NUM_DOUBLE);
	}
yy199:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy198;
			if (yych <= '9') goto yy199;
			goto yy198;
		} else {
			if (yych <= 'E') goto yy194;
			if (yych == 'e') goto yy194;
			goto yy198;
		}
yy201:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy202:
		if (yybm[0+yych] & 2) {
			goto yy201;
		}
		if (yych <= '9') {
			if (yych == '.') goto yy191;
			if (yych <= '/') goto yy24;
			goto yy192;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy24;
				goto yy194;
			} else {
				if (yych == 'e') goto yy194;
				goto yy24;
			}
		}
yy203:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy204;
		}
		goto yy136;
yy204:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy204;
		}
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex + 2);
		int64_t n = 0;

		for (int i = 0; i < yylen - 2; ++i) {
			n <<= 4;
			if (isdigit(nstr[i])) {
				n += nstr[i] - '0';
			}
			else {
				n += toupper(nstr[i]) - 'A' + 10;
			}
		}

        yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy207:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_MULTILINE_COMMENT);
		SKIP();
	}
yy209:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy211:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DIV_EQUAL); }
yy213:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy198;
			if (yych <= '9') goto yy213;
			goto yy198;
		} else {
			if (yych <= 'E') goto yy194;
			if (yych == 'e') goto yy194;
			goto yy198;
		}
yy215:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych == '.') goto yy191;
		if (yych <= '/') goto yy136;
		if (yych <= '9') goto yy215;
		goto yy136;
yy217:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy136;
		if (yych <= '9') goto yy213;
		goto yy136;
yy218:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MINUS_EQUAL); }
yy220:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DEC); }
yy222:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::PLUS_EQUAL); }
yy224:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::INC); }
yy226:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MULT_EQUAL); }
yy228:
		++YYCURSOR;
		yych = *YYCURSOR;
yy229:
		if (yybm[0+yych] & 8) {
			goto yy228;
		}
		if (yych >= '\\') goto yy232;
yy230:
		++YYCURSOR;
yy231:
		{ yylen = cursor - s.yylex; }
		{
		std::string strtext(reinterpret_cast<const char*>(s.yylex+1), yylen-2);
		size_t found = 0;

		// Handle sequence char
		while (1) {
			found = strtext.find('\\', found);
			if (found == std::string::npos) {
				break;
			}
			if (s.yylex[0] == '"') {
				switch (strtext[found+1]) {
					case 'n': strtext.replace(found, 2, 1, '\n'); break;
					case 'r': strtext.replace(found, 2, 1, '\r'); break;
					case 't': strtext.replace(found, 2, 1, '\t'); break;
					case 'v': strtext.replace(found, 2, 1, '\v'); break;
					case '"': strtext.replace(found, 2, 1, '"'); break;
					case '\\': strtext.replace(found, 2, 1, '\\'); ++found; break;
					default: ++found; break;
				}
			} else {
				switch (strtext[found+1]) {
					case '\'': strtext.replace(found, 2, 1, '\''); break;
					default: ++found; break;
				}
			}
		}

        yylval->strlit = new ast::StringLit(CSTRING(strtext), *yyloc);

		RET(token::STR);
	}
yy232:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy228;
		}
		if (yych >= '\\') goto yy232;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy228;
		}
		if (yych <= '[') goto yy230;
		goto yy232;
yy235:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_AND_EQUAL); }
yy237:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_AND); }
yy239:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MOD_EQUAL); }
yy241:
		++YYCURSOR;
		yych = *YYCURSOR;
yy242:
		if (yybm[0+yych] & 32) {
			goto yy241;
		}
		if (yych <= '[') goto yy230;
yy243:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy241;
		}
		if (yych >= '\\') goto yy243;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy241;
		}
		if (yych <= '[') goto yy230;
		goto yy243;
yy246:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::NOT_EQUAL); }
yy248:
		++YYCURSOR;
		yych = *YYCURSOR;
yy249:
		if (yybm[0+yych] & 64) {
			goto yy248;
		}
		goto yy8;
yy250:
		++YYCURSOR;
		yych = *YYCURSOR;
yy251:
		if (yybm[0+yych] & 128) {
			goto yy250;
		}
		goto yy6;
	}
/* *********************************** */
yyc_ST_COMMENT:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,  32, 192,  64, 192,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yych <= '\v') {
			if (yych <= 0x08) {
				if (yych <= 0x00) goto yy255;
				goto yy256;
			} else {
				if (yych == '\n') goto yy258;
				goto yy257;
			}
		} else {
			if (yych <= '\r') {
				if (yych <= '\f') goto yy256;
				goto yy257;
			} else {
				if (yych == ' ') goto yy257;
				goto yy256;
			}
		}
yy254:
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy255:
		yych = *++YYCURSOR;
		goto yy263;
yy256:
		yych = *++YYCURSOR;
		goto yy263;
yy257:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy264;
		}
		if (yych == '\n') goto yy254;
		goto yy262;
yy258:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy261;
yy259:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy260:
		++YYCURSOR;
		yych = *YYCURSOR;
yy261:
		if (yybm[0+yych] & 32) {
			goto yy260;
		}
		goto yy259;
yy262:
		++YYCURSOR;
		yych = *YYCURSOR;
yy263:
		if (yybm[0+yych] & 64) {
			goto yy262;
		}
		goto yy254;
yy264:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy264;
		}
		if (yych == '\n') goto yy254;
		goto yy262;
	}
/* *********************************** */
yyc_ST_MULTILINE_COMMENT:
	{
		static const unsigned char yybm[] = {
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32, 160,  96, 160,  32, 160,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			160,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,   0,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
		};
		yych = *YYCURSOR;
		if (yych <= '\f') {
			if (yych <= '\t') {
				if (yych <= 0x00) goto yy268;
				if (yych <= 0x08) goto yy270;
				goto yy271;
			} else {
				if (yych <= '\n') goto yy272;
				if (yych <= '\v') goto yy271;
				goto yy270;
			}
		} else {
			if (yych <= ' ') {
				if (yych <= '\r') goto yy271;
				if (yych <= 0x1F) goto yy270;
				goto yy271;
			} else {
				if (yych == '*') goto yy273;
				goto yy270;
			}
		}
yy268:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy278;
yy269:
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy270:
		yych = *++YYCURSOR;
		goto yy278;
yy271:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy281;
		}
		goto yy278;
yy272:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy279;
		}
		goto yy278;
yy273:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '/') goto yy275;
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy275:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy277:
		++YYCURSOR;
		yych = *YYCURSOR;
yy278:
		if (yybm[0+yych] & 32) {
			goto yy277;
		}
		goto yy269;
yy279:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy279;
		}
		if (yych == '*') goto yy269;
		goto yy277;
yy281:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy281;
		}
		if (yych == '*') goto yy269;
		goto yy277;
	}
}

}

} // clever
