/* Generated by re2c 0.13.5 */
/**
 * Clever programming language
 * Copyright (c) Clever Team
 *
 * This file is distributed under the MIT license. See LICENSE for details.
 */

#include <cstdio>
#include "core/scanner.h"
#include "core/parser.hh"
#include "core/ast.h"
#include "core/value.h"
#include "types/native_types.h"

namespace clever {

typedef Parser::token token;

Parser::token_type yylex(Parser::semantic_type* yylval,
	Parser::location_type* yyloc, Driver& driver, ScannerState& s) {
	const unsigned char* cursor = s.cur;
	int yylen;

next_token:
	if (YYCURSOR >= YYLIMIT) {
		RET(token::END);
	}

	s.yylex = cursor;


{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if (YYGETCONDITION() < 1) {
		goto yyc_INITIAL;
	} else {
		if (YYGETCONDITION() < 2) {
			goto yyc_ST_COMMENT;
		} else {
			goto yyc_ST_MULTILINE_COMMENT;
		}
	}
/* *********************************** */
yyc_INITIAL:
	{
		static const unsigned char yybm[] = {
			/* table 1 .. 8: 0 */
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40, 168, 104, 168,  40, 168,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			168,  40,   8,  40,  40,  40,  40,  32, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 47,  47,  47,  47,  47,  47,  47,  47, 
			 45,  45,  40,  40,  40,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  16,  40,  40,  40, 
			 40,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  44,  44,  44,  44,  44, 
			 44,  44,  44,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			 40,  40,  40,  40,  40,  40,  40,  40, 
			/* table 9 .. 10: 256 */
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192,   0,   0,   0,   0,   0,   0, 
			  0, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192, 192, 192, 192, 192, 192, 
			192, 192, 192,   0,   0,   0,   0, 192, 
			  0,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};

		yych = *YYCURSOR;
		switch (yych) {
		case 0x00:	goto yy2;
		case '\t':
		case '\v':
		case '\r':
		case ' ':	goto yy5;
		case '\n':	goto yy7;
		case '!':	goto yy9;
		case '"':	goto yy10;
		case '#':	goto yy11;
		case '%':	goto yy13;
		case '&':	goto yy14;
		case '\'':	goto yy16;
		case '(':
		case ')':
		case ',':
		case ';':
		case '{':
		case '}':
		case '~':	goto yy17;
		case '*':	goto yy18;
		case '+':	goto yy19;
		case '-':	goto yy20;
		case '.':	goto yy21;
		case '/':	goto yy22;
		case '0':	goto yy23;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy25;
		case '<':	goto yy26;
		case '=':	goto yy28;
		case '>':	goto yy29;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':	goto yy31;
		case '^':	goto yy33;
		case 'a':	goto yy34;
		case 'b':	goto yy36;
		case 'c':	goto yy37;
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'u':
		case 'x':
		case 'y':
		case 'z':	goto yy38;
		case 'e':	goto yy39;
		case 'f':	goto yy40;
		case 'i':	goto yy41;
		case 'n':	goto yy42;
		case 'o':	goto yy43;
		case 'r':	goto yy44;
		case 's':	goto yy45;
		case 't':	goto yy46;
		case 'v':	goto yy47;
		case 'w':	goto yy48;
		case '|':	goto yy49;
		default:	goto yy4;
		}
yy2:
		++YYCURSOR;
yy3:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy4:
		yych = *++YYCURSOR;
		goto yy3;
yy5:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy250;
yy6:
		{ yylen = cursor - s.yylex; }
		{ yyloc->step(); SKIP(); }
yy7:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy248;
yy8:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy9:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy245;
		goto yy3;
yy10:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy241;
yy11:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy13:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy238;
		goto yy3;
yy14:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '&') goto yy236;
		if (yych == '=') goto yy234;
yy15:
		{ yylen = cursor - s.yylex; }
		{ RET(Parser::token_type(s.yylex[0])); }
yy16:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy228;
yy17:
		yych = *++YYCURSOR;
		goto yy15;
yy18:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy225;
		goto yy15;
yy19:
		yych = *++YYCURSOR;
		if (yych == '+') goto yy223;
		if (yych == '=') goto yy221;
		goto yy15;
yy20:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') {
			if (yych <= ',') goto yy15;
			if (yych <= '-') goto yy219;
			if (yych <= '.') goto yy216;
			goto yy15;
		} else {
			if (yych <= '9') goto yy214;
			if (yych == '=') goto yy217;
			goto yy15;
		}
yy21:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy212;
		goto yy3;
yy22:
		yych = *++YYCURSOR;
		if (yych <= '.') {
			if (yych == '*') goto yy206;
			goto yy15;
		} else {
			if (yych <= '/') goto yy208;
			if (yych == '=') goto yy210;
			goto yy15;
		}
yy23:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'x') goto yy202;
		goto yy201;
yy24:
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex);
		int64_t n = 0;

		for (int i = 0; i < yylen; ++i) {
			n = n * 10 + (nstr[i] - '0');
		}

        yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy25:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy192;
yy26:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= ';') goto yy27;
		if (yych <= '<') goto yy184;
		if (yych <= '=') goto yy186;
yy27:
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS); }
yy28:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy182;
		goto yy15;
yy29:
		++YYCURSOR;
		if ((yych = *YYCURSOR) <= '<') goto yy30;
		if (yych <= '=') goto yy178;
		if (yych <= '>') goto yy176;
yy30:
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER); }
yy31:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy172;
yy32:
		{ yylen = cursor - s.yylex; }
		{
		yylval->ident = new ast::Ident(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);

		RET(token::CONSTANT);
	}
yy33:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy169;
		goto yy15;
yy34:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == 'n') goto yy166;
		goto yy55;
yy35:
		{ yylen = cursor - s.yylex; }
		{
		yylval->ident = new ast::Ident(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);

		RET(token::IDENT);
	}
yy36:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy161;
		goto yy55;
yy37:
		yych = *++YYCURSOR;
		if (yych <= 'n') {
			if (yych == 'a') goto yy137;
			goto yy55;
		} else {
			if (yych <= 'o') goto yy138;
			if (yych == 'r') goto yy139;
			goto yy55;
		}
yy38:
		yych = *++YYCURSOR;
		goto yy55;
yy39:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy126;
		goto yy55;
yy40:
		yych = *++YYCURSOR;
		if (yych <= 'i') {
			if (yych == 'a') goto yy103;
			if (yych <= 'h') goto yy55;
			goto yy104;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy55;
				goto yy105;
			} else {
				if (yych == 'u') goto yy106;
				goto yy55;
			}
		}
yy41:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy95;
		if (yych == 'm') goto yy97;
		goto yy55;
yy42:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy88;
		if (yych == 'u') goto yy89;
		goto yy55;
yy43:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy86;
		goto yy55;
yy44:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy80;
		goto yy55;
yy45:
		yych = *++YYCURSOR;
		if (yych == 'p') goto yy75;
		goto yy55;
yy46:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy64;
		if (yych == 'r') goto yy65;
		goto yy55;
yy47:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy61;
		goto yy55;
yy48:
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy56;
		goto yy55;
yy49:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy50;
		if (yych == '|') goto yy52;
		goto yy15;
yy50:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_OR_EQUAL); }
yy52:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_OR); }
yy54:
		++YYCURSOR;
		yych = *YYCURSOR;
yy55:
		if (yybm[256+yych] & 64) {
			goto yy54;
		}
		goto yy35;
yy56:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::WHILE);
	}
yy61:
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::VAR); }
yy64:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy71;
		goto yy55;
yy65:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy68;
		if (yych != 'y') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::TRY); }
yy68:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->true_ = new ast::TrueLit(*yyloc);
		RET(token::TRUE);
	}
yy71:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::THROW); }
yy75:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::THREAD);
	}
yy80:
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::RETURN);
	}
yy86:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_OR); }
yy88:
		yych = *++YYCURSOR;
		if (yych == 'w') goto yy93;
		goto yy55;
yy89:
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->nillit = new ast::NullLit(*yyloc);
		RET(token::NIL);
	}
yy93:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::NEW);
	}
yy95:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IF);
	}
yy97:
		yych = *++YYCURSOR;
		if (yych != 'p') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::IMPORT);
	}
yy103:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy122;
		goto yy55;
yy104:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy116;
		goto yy55;
yy105:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy114;
		goto yy55;
yy106:
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FUNC);
	}
yy114:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::FOR);
	}
yy116:
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'y') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::FINALLY); }
yy122:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		yylval->false_ = new ast::FalseLit(*yyloc);
		RET(token::FALSE);
	}
yy126:
		yych = *++YYCURSOR;
		if (yych != 's') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'Z') {
			if (yych <= '/') {
				if (yych == ' ') goto yy131;
			} else {
				if (yych <= '9') goto yy54;
				if (yych >= 'A') goto yy54;
			}
		} else {
			if (yych <= '`') {
				if (yych == '_') goto yy54;
			} else {
				if (yych == 'i') goto yy130;
				if (yych <= 'z') goto yy54;
			}
		}
yy129:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSE);
	}
yy130:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy136;
		goto yy55;
yy131:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy133;
yy132:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy3;
				} else {
					goto yy15;
				}
			} else {
				goto yy24;
			}
		} else {
			if (yyaccept <= 4) {
				if (yyaccept <= 3) {
					goto yy129;
				} else {
					goto yy197;
				}
			} else {
				goto yy230;
			}
		}
yy133:
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy132;
		++YYCURSOR;
yy135:
		{ yylen = cursor - s.yylex; }
		{
		RET(token::ELSEIF);
	}
yy136:
		yych = *++YYCURSOR;
		if (yybm[256+yych] & 64) {
			goto yy54;
		}
		goto yy135;
yy137:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy157;
		goto yy55;
yy138:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy147;
		goto yy55;
yy139:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 't') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::CRITICAL);
	}
yy147:
		yych = *++YYCURSOR;
		if (yych <= 'r') goto yy55;
		if (yych <= 's') goto yy148;
		if (yych <= 't') goto yy149;
		goto yy55;
yy148:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy155;
		goto yy55;
yy149:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONTINUE); }
yy155:
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CONST); }
yy157:
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::CATCH); }
yy161:
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy55;
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{
		RET(token::BREAK);
	}
yy166:
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy55;
		++YYCURSOR;
		if (yybm[256+(yych = *YYCURSOR)] & 64) {
			goto yy54;
		}
		{ yylen = cursor - s.yylex; }
		{ RET(token::LOGICAL_AND); }
yy169:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::XOR_EQUAL); }
yy171:
		++YYCURSOR;
		yych = *YYCURSOR;
yy172:
		if (yybm[256+yych] & 128) {
			goto yy171;
		}
		if (yych <= '`') goto yy32;
		if (yych >= '{') goto yy32;
yy173:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'Z') {
			if (yych <= '/') goto yy175;
			if (yych <= '9') goto yy173;
			if (yych >= 'A') goto yy173;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yy173;
			} else {
				if (yych <= '`') goto yy175;
				if (yych <= 'z') goto yy173;
			}
		}
yy175:
		{ yylen = cursor - s.yylex; }
		{
		yylval->type = new ast::Type(
			CSTRING(std::string(reinterpret_cast<const char*>(s.yylex), yylen)), *yyloc);
		RET(token::TYPE);
	}
yy176:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy180;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT); }
yy178:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::GREATER_EQUAL); }
yy180:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::RSHIFT_EQUAL); }
yy182:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::EQUAL); }
yy184:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy188;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT); }
yy186:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LESS_EQUAL); }
yy188:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::LSHIFT_EQUAL); }
yy190:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy132;
		if (yych <= '9') goto yy198;
		goto yy132;
yy191:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy192:
		if (yybm[0+yych] & 1) {
			goto yy191;
		}
		if (yych <= 'D') {
			if (yych == '.') goto yy190;
			goto yy24;
		} else {
			if (yych <= 'E') goto yy193;
			if (yych != 'e') goto yy24;
		}
yy193:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych != '+') goto yy132;
		} else {
			if (yych <= '-') goto yy194;
			if (yych <= '/') goto yy132;
			if (yych <= '9') goto yy195;
			goto yy132;
		}
yy194:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy132;
		if (yych >= ':') goto yy132;
yy195:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= '/') goto yy197;
		if (yych <= '9') goto yy195;
yy197:
		{ yylen = cursor - s.yylex; }
		{
		double n = strtod(
			std::string(reinterpret_cast<const char*>(s.yylex), yylen).c_str(), NULL);

        yylval->dbllit = new ast::DoubleLit(n, *yyloc);

		RET(token::NUM_DOUBLE);
	}
yy198:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy197;
			if (yych <= '9') goto yy198;
			goto yy197;
		} else {
			if (yych <= 'E') goto yy193;
			if (yych == 'e') goto yy193;
			goto yy197;
		}
yy200:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy201:
		if (yybm[0+yych] & 2) {
			goto yy200;
		}
		if (yych <= '9') {
			if (yych == '.') goto yy190;
			if (yych <= '/') goto yy24;
			goto yy191;
		} else {
			if (yych <= 'E') {
				if (yych <= 'D') goto yy24;
				goto yy193;
			} else {
				if (yych == 'e') goto yy193;
				goto yy24;
			}
		}
yy202:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy203;
		}
		goto yy132;
yy203:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy203;
		}
		{ yylen = cursor - s.yylex; }
		{
		const char* nstr = reinterpret_cast<const char*>(s.yylex + 2);
		int64_t n = 0;

		for (int i = 0; i < yylen - 2; ++i) {
			n <<= 4;
			if (isdigit(nstr[i])) {
				n += nstr[i] - '0';
			}
			else {
				n += toupper(nstr[i]) - 'A' + 10;
			}
		}

        yylval->intlit = new ast::IntLit(n, *yyloc);

		RET(token::NUM_INTEGER);
	}
yy206:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_MULTILINE_COMMENT);
		SKIP();
	}
yy208:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(ST_COMMENT);
		SKIP();
	}
yy210:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DIV_EQUAL); }
yy212:
		yyaccept = 4;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '/') goto yy197;
			if (yych <= '9') goto yy212;
			goto yy197;
		} else {
			if (yych <= 'E') goto yy193;
			if (yych == 'e') goto yy193;
			goto yy197;
		}
yy214:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yych == '.') goto yy190;
		if (yych <= '/') goto yy132;
		if (yych <= '9') goto yy214;
		goto yy132;
yy216:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy132;
		if (yych <= '9') goto yy212;
		goto yy132;
yy217:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MINUS_EQUAL); }
yy219:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::DEC); }
yy221:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::PLUS_EQUAL); }
yy223:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::INC); }
yy225:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MULT_EQUAL); }
yy227:
		++YYCURSOR;
		yych = *YYCURSOR;
yy228:
		if (yybm[0+yych] & 8) {
			goto yy227;
		}
		if (yych >= '\\') goto yy231;
yy229:
		++YYCURSOR;
yy230:
		{ yylen = cursor - s.yylex; }
		{
		std::string strtext(reinterpret_cast<const char*>(s.yylex+1), yylen-2);
		size_t found = 0;

		// Handle sequence char
		while (1) {
			found = strtext.find('\\', found);
			if (found == std::string::npos) {
				break;
			}
			if (s.yylex[0] == '"') {
				switch (strtext[found+1]) {
					case 'n': strtext.replace(found, 2, 1, '\n'); break;
					case 'r': strtext.replace(found, 2, 1, '\r'); break;
					case 't': strtext.replace(found, 2, 1, '\t'); break;
					case 'v': strtext.replace(found, 2, 1, '\v'); break;
					case '"': strtext.replace(found, 2, 1, '"'); break;
					case '\\': strtext.replace(found, 2, 1, '\\'); ++found; break;
					default: ++found; break;
				}
			} else {
				switch (strtext[found+1]) {
					case '\'': strtext.replace(found, 2, 1, '\''); break;
					default: ++found; break;
				}
			}
		}

        yylval->strlit = new ast::StringLit(CSTRING(strtext), *yyloc);

		RET(token::STR);
	}
yy231:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy227;
		}
		if (yych >= '\\') goto yy231;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy227;
		}
		if (yych <= '[') goto yy229;
		goto yy231;
yy234:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BW_AND_EQUAL); }
yy236:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::BOOLEAN_AND); }
yy238:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::MOD_EQUAL); }
yy240:
		++YYCURSOR;
		yych = *YYCURSOR;
yy241:
		if (yybm[0+yych] & 32) {
			goto yy240;
		}
		if (yych <= '[') goto yy229;
yy242:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy240;
		}
		if (yych >= '\\') goto yy242;
		yyaccept = 5;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy240;
		}
		if (yych <= '[') goto yy229;
		goto yy242;
yy245:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{ RET(token::NOT_EQUAL); }
yy247:
		++YYCURSOR;
		yych = *YYCURSOR;
yy248:
		if (yybm[0+yych] & 64) {
			goto yy247;
		}
		goto yy8;
yy249:
		++YYCURSOR;
		yych = *YYCURSOR;
yy250:
		if (yybm[0+yych] & 128) {
			goto yy249;
		}
		goto yy6;
	}
/* *********************************** */
yyc_ST_COMMENT:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,  32, 192,  64, 192,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yych <= '\v') {
			if (yych <= 0x08) {
				if (yych <= 0x00) goto yy254;
				goto yy255;
			} else {
				if (yych == '\n') goto yy257;
				goto yy256;
			}
		} else {
			if (yych <= '\r') {
				if (yych <= '\f') goto yy255;
				goto yy256;
			} else {
				if (yych == ' ') goto yy256;
				goto yy255;
			}
		}
yy253:
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy254:
		yych = *++YYCURSOR;
		goto yy262;
yy255:
		yych = *++YYCURSOR;
		goto yy262;
yy256:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy263;
		}
		if (yych == '\n') goto yy253;
		goto yy261;
yy257:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy260;
yy258:
		{ yylen = cursor - s.yylex; }
		{
		if (YYGETCONDITION() == yycST_COMMENT) {
			YYSETCONDITION(INITIAL);
		}
		yyloc->lines(yylen);
		yyloc->step();
		SKIP();
	}
yy259:
		++YYCURSOR;
		yych = *YYCURSOR;
yy260:
		if (yybm[0+yych] & 32) {
			goto yy259;
		}
		goto yy258;
yy261:
		++YYCURSOR;
		yych = *YYCURSOR;
yy262:
		if (yybm[0+yych] & 64) {
			goto yy261;
		}
		goto yy253;
yy263:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy263;
		}
		if (yych == '\n') goto yy253;
		goto yy261;
	}
/* *********************************** */
yyc_ST_MULTILINE_COMMENT:
	{
		static const unsigned char yybm[] = {
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32, 160,  96, 160,  32, 160,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			160,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,   0,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
		};
		yych = *YYCURSOR;
		if (yych <= '\f') {
			if (yych <= '\t') {
				if (yych <= 0x00) goto yy267;
				if (yych <= 0x08) goto yy269;
				goto yy270;
			} else {
				if (yych <= '\n') goto yy271;
				if (yych <= '\v') goto yy270;
				goto yy269;
			}
		} else {
			if (yych <= ' ') {
				if (yych <= '\r') goto yy270;
				if (yych <= 0x1F) goto yy269;
				goto yy270;
			} else {
				if (yych == '*') goto yy272;
				goto yy269;
			}
		}
yy267:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy277;
yy268:
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy269:
		yych = *++YYCURSOR;
		goto yy277;
yy270:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy280;
		}
		goto yy277;
yy271:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy278;
		}
		goto yy277;
yy272:
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '/') goto yy274;
		{ yylen = cursor - s.yylex; }
		{ SKIP(); }
yy274:
		++YYCURSOR;
		{ yylen = cursor - s.yylex; }
		{
		YYSETCONDITION(INITIAL);
		SKIP();
	}
yy276:
		++YYCURSOR;
		yych = *YYCURSOR;
yy277:
		if (yybm[0+yych] & 32) {
			goto yy276;
		}
		goto yy268;
yy278:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy278;
		}
		if (yych == '*') goto yy268;
		goto yy276;
yy280:
		++YYCURSOR;
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy280;
		}
		if (yych == '*') goto yy268;
		goto yy276;
	}
}

}

} // clever
